import React from "react";
import Head from "next/head";
import Image from "next/image";
import Layout from "@/components/Layout";
import Footer from "@/components/Footer";
import whoami from "/home/govind/Projects/Portfolio/public/images/profile/whoami.png";
import profilepic from "/home/govind/Projects/Portfolio/public/images/profile/main.png";
import AnimatedText from "@/components/AnimatedText";
import design from "/home/govind/Projects/Portfolio/public/images/designing.png";
import camera from "/home/govind/Projects/Portfolio/public/images/profile/cam.png";
import web from "/home/govind/Projects/Portfolio/public/images/profile/web.png";


import game from "/home/govind/Projects/Portfolio/public/images/profile/game.png";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {

  return (
    <>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark  sm:overflow-x-hidden">
      <Layout>
  <div className="flex flex-col sm:flex-row items-center justify-between w-full sm:h-[800px] h-[600px]">
    <div className="w-full sm:w-1/2 sm:mt-[-21%] mb-6 sm:mb-0">
      <h1 className="font-helvetica-neue text-5xl sm:text-8xl  sm:w-90% font-extrabold text-left sm:text-left">
        <AnimatedText text="Coding the Pixels,"></AnimatedText>
        <AnimatedText text="Capturing the Moments"></AnimatedText>
      </h1>
    </div>

    <div className="w-full sm:w-1/2 mt-6 sm:mt-0">
      <Image
        src={profilepic}
        alt="programmer"
        className="w-full h-auto sm:mt-[-50%] sm:p-[100px] sm:ml-[170px] mx-auto"
      />
    </div>
  </div>

  <div className="flex flex-col max-h-[1000px] w-full sm:flex-row">
    <div className="w-full sm:w-1/2 mt-6 sm:mt-0">
      <Image
        src={whoami}
        alt="programmer"
        className="w-full sm:p-[100px] sm:ml-[-130px] sm:mt-[-150px] filter grayscale mx-auto"
      />
    </div>
    <p className="font-mont sm:w-[80%] py-5  sm:text-right text-right text-sm sm:text-2xl w-full">
      Hey, I’m Govind Krishna, currently pursuing B.Tech in Computer Science at Amrita University. While my academic journey involves studying Computer Science, my true passion lies in the creative realm of UI/UX design.

      I thrive on crafting intuitive and visually appealing user interfaces, ensuring seamless user experiences. Beyond the digital world, you'll often find me immersed in the art of drawing intricate designs, fine-tuning photos with my editing skills, and strumming the guitar to create soulful melodies.

      As a member of AmFOSS (Amrita Free and Open Source Software), I actively contribute to the open-source community, blending my creative flair with technology. Let's merge the worlds of design, art, and technology to create captivating and immersive experiences together.
    </p>x
  </div>

  <div className="w-full sm:h-[400px] h-[1200px] overflow-y-hidden">
  <h1 className="font-helvetica-neue text-4xl font-extrabold text-center pt-6 sm:pt-12">INTERESTS</h1>
  <div className="w-full flex flex-col items-center justify-center sm:flex-row sm:justify-between mx-auto font-denk fi  p-8">
    <div className="text-center mb-4 sm:mb-0">
      <Image
        src={camera}
        alt="camera"
        className="w-[200px] h-[200px] "
      />
      <p className="mt-2">Photography</p>
    </div>

    <div className="text-center mb-4 sm:mb-0">
      <Image
        src={web}
        alt="web"
        className="w-[200px] h-[200px] "
      />
      <p className="mt-2">Web Developer</p>
    </div>

    <div className="text-center mb-4 sm:mb-0">
      <Image
        src={game}
        alt="game"
        className="w-[200px] h-[200px] "
      />
      <p className="mt-2">Games</p>
    </div>
    <div className="text-center mb-4 sm:mb-0">
      <Image
        src={design}
        alt="game"
        className="w-[200px] h-[200px]"
      />
      <p className="mt-2">Designing</p>
    </div>
  </div>
</div>


</Layout>

</main>
<Footer></Footer>
    </>
  );
}
